# Generated by Django 6.0.1 on 2026-01-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profession_user_residence_alter_user_last_login"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="otpcode",
            name="otp_codes_user_id_c67bdc_idx",
        ),
        migrations.DeleteModel(
            name="OTPCode",
        ),
    ]
